- docs/pull_request_template.md
> feat: add template on pull request

- android/build.gradle
- android/src/main/AndroidManifest.xml
- android/src/main/kotlin/com/unico_check/CameraActivity.kt
- android/src/main/kotlin/com/unico_check/DocumentCameraActivity.kt
- android/src/main/kotlin/com/unico_check/SelfieCameraActivity.kt
- android/src/main/kotlin/com/unico_check/UnicoCheckPlugin.kt
- android/src/main/kotlin/com/unico_check/config/UnicoTheme.kt
- android/src/main/kotlin/com/unico_check/config/UnicoTimer.kt
- android/src/main/kotlin/com/unico_check/constants/MethodConstants.kt
- android/src/main/kotlin/com/unico_check/constants/ReturnConstants.kt
- android/src/main/kotlin/com/unico_check/hashMap/ConvertAcessoBioHashMap.kt
> update sdk android in module native 
> update to sdk version 4.0.14
> n/a
> n/a
> [Issue ID related with this PR](https://unicoidtech.atlassian.net/browse/CM-274)
> feat: update android native module

- lib/src/clean/adapter/api/unico.check.builder.default.dart
- lib/src/clean/adapter/api/unico.check.camera.opener.default.dart
- lib/src/clean/adapter/repository/channel.repository.default.dart
- lib/src/clean/domain/entities/unico.config.dart
- lib/src/clean/domain/usecase/open.camera.usecase.default.dart
- lib/src/clean/domain/usecase/unico.callback.usecase.dart
- lib/src/clean/plugins/channel/channel.unico.default.dart
> implementation callbacks 
> create implementation of new estructure
> n/a
> n/a
> [Issue ID related with this PR
](https://unicoidtech.atlassian.net/browse/CM-231)
> feat: add implementations

- CHANGELOG.md
- example/lib/main.dart
- example/pubspec.lock
- lib/src/unico/adapter/api/unico.check.builder.dart
- lib/src/unico/adapter/api/unico.check.builder.default.dart
> receive configuration by the builder
> UnicoCheck
> flutter test
> n/a
> feat: update config

- android/src/main/AndroidManifest.xml
- android/src/main/kotlin/com/unico_check/CameraActivity.kt
- android/src/main/kotlin/com/unico_check/constants/VersionTag.kt
- lib/src/unico/adapter/api/unico.check.camera.opener.default.dart
- lib/src/unico/adapter/repository/channel.repository.default.dart
- lib/src/unico/adapter/repository/mappers/open.camera.request.mapper.dart
- lib/src/unico/adapter/repository/mappers/unico.theme.mapper.dart
- lib/src/unico/di/module.dart
- lib/src/unico/domain/entities/open_camera/open.camera.config.entity.dart
- lib/src/unico/domain/usecase/unico.callback.usecase.dart
- test/src/test_dummy.dart
- test/src/unico/adapter/api/unico.check.builder.default_test.dart
- test/src/unico/adapter/api/unico.check.camera.opener.default_test.dart
- test/src/unico/domain/mapper/open.camera.request.mapper_test.dart
- test/src/unico/domain/mapper/unico.error.factory_test.dart
- test/src/unico/domain/mapper/unico.theme.mapper_test.dart
- test/src/unico/domain/usecase/unico.callback.usecase_test.dart
- test/src/unico/plugins/channel/channel.unico.default_test.dart
- test/src/unico/repository/channel.repository.default_test.dart
- test/src/unico/repository/processors/camera.result.processor.mapper_test.dart
> open camera document was not open and format code dart conventions
> Document camera and code format
> flutter test
> n/a
> [Issue ID related with this PR](https://unicoidtech.atlassian.net/browse/CM-716)
> fix: open camera document was not open and format code dart conventions

- ios/Classes/config/UnicoTheme.swift
> Ios theme was not worck
> UnicoTheme in ios
> n/a
> n/a
> fix: theme ios

- CHANGELOG.md
- android/build.gradle
- example/ios/Podfile.lock
- example/ios/Runner.xcodeproj/project.pbxproj
- example/pubspec.lock
- ios/unico_check.podspec
- pubspec.yaml
> Update liveness ativo and fix bug google-service json
> Update liveness ativo and fix bug google-service json
> flutter test
> https://unicoidtech.atlassian.net/browse/CM-772
> feat: update android ios

- CHANGELOG.md
- android/build.gradle
- example/ios/Podfile.lock
- example/ios/Runner.xcodeproj/project.pbxproj
- example/lib/main.dart
- example/pubspec.lock
- ios/unico_check.podspec
- pubspec.yaml
> 
feat: Update android 4.2.0 and ios 2.3.7
fix: Document example 
> build.gradle, Podfile.lock and Main.dart
> flutter test
> 
https://unicoidtech.atlassian.net/browse/SD-190
https://unicoidtech.atlassian.net/browse/SD-220
https://unicoidtech.atlassian.net/browse/SD-221
> feat: update andrdoid ios 3.0.2

- android/build.gradle
- example/ios/Podfile.lock
- example/ios/Runner.xcodeproj/project.pbxproj
- example/ios/Runner/Info.plist
- ios/Classes/AcessoBioCamera.swift
- ios/Classes/AcessoBioDocument.swift
- ios/Classes/AcessoBioView.swift
- ios/unico_check.podspec
> Update android to 4.2.9 version and ios to 2.3.10 add suport to IOS 14
> Android and IOS Native module
> flutter test
> feat(SD-368): Update android and ios

- CHANGELOG.md
- android/build.gradle
- pubspec.yaml
> fix error android
> update android
> flutter run test
> feat: Update Android Version to 4.2.8

- android/build.gradle
- example/ios/Podfile.lock
- example/ios/Runner.xcodeproj/project.pbxproj
- ios/unico_check.podspec
> update libs android and Ios
> gradlew and podspac
> flutter test
> feat: update native libs

- CHANGELOG.md
- android/build.gradle
- pubspec.yaml
> Update android, update facetec
> update android
> flutter test
> [ Issue ID related with this PR
](https://unicoidtech.atlassian.net/browse/SD-619)
> feat(SD-619): update android to 4.2.12

- CHANGELOG.md
- android/build.gradle
- android/src/main/kotlin/com/unico_check/CameraActivity.kt
- android/src/main/kotlin/com/unico_check/CameraView.kt
- android/src/main/kotlin/com/unico_check/permission/CameraPermissionActivity.kt
- example/pubspec.lock
- pubspec.lock
- pubspec.yaml
> Improve user experience
> native android
> flutter test 
https://user-images.githubusercontent.com/74009931/233481509-9ab0c5d1-dbaf-4f2e-a654-f07ed2294891.mp4
> fix(SD-681): black screan

- .github/workflows/on_pull_request.yaml
- android/build.gradle
- example/ios/Podfile.lock
- example/ios/Runner.xcodeproj/project.pbxproj
- example/lib/main.dart
- example/pubspec.lock
- example/pubspec.yaml
- ios/unico_check.podspec
- lib/src/unico/adapter/repository/mappers/open.camera.request.mapper.dart
- pubspec.lock
- pubspec.yaml
> Update Android and IOS
> Build.gradle and unico_check.podspec
> Update suport dart ">=2.15.0 <3.0.0"
> Flutter test 
> n/a
> [Issue ID related with this PR](https://unicoidtech.atlassian.net/jira/software/c/projects/SD/boards/449?modal=detail&selectedIssue=SD-772&assignee=5fa1a75cdbf337006cc0e167)
> feat(SD-772): Update Android to 4.4.0 and IOS to 2.3.18

- CHANGELOG.md
- pubspec.yaml
> feat: update log

- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
- example/android/app/src/main/AndroidManifest.xml
- example/android/build.gradle
- example/android/gradle/wrapper/gradle-wrapper.properties
Atualizado gradle plugin para versão 7.4.2, gradle para versão 7.5 e o compile sdk para versão 31
> Atualizado gradle plugin para 7.4.2
> Atualizado gradle plugin para 7.5
> Atualizado compile sdk para 31
> Rodar o app de exemplo
> chore: update gradle sdk and compile version

- CHANGELOG.md
- ios/unico_check.podspec
- pubspec.yaml
> Update flutter plugin
> Update IOS version 
> Update environment: sdk: ">=2.15.0 <4.0.0" ( flutter pub publish --dry-run  )
> flutter test
> feat: Update native IOS 2.3.20

- android/build.gradle
Esse PR tem o objetivo de atualizar a versão do SDK Android do projeto de 5.0.0 para 5.1.2
> Android SDK da versão 5.0.0 para 5.1.2
> chore: Update Android SDK version 5.0.0 to 5.1.2

- ios/unico_check.podspec
Update flutter sdk
Update  native iOS version
Update version
n/a
n/a
n/a
> feat: update ios native dependency

- CHANGELOG.md
> update change log
> change log
> feat: change log

- pubspec.yaml
> feat: update-version

- ios/unico_check.podspec
> Update iOS SDK to 2.3.24
> Update unico_check.podspec version to 2.0.4
> Update unicocheck-ios dependency to 2.3.24.
> Update unicocheck-ios dependency to 2.3.24.

- CHANGELOG.md
- android/build.gradle
- ios/Classes/config/UnicoConfig.swift
- ios/Classes/constants/MethodConstansts.swift
- pubspec.yaml
> Describe what motivates you to submit this change
> List all changes made
> Describe how to test this change (optional)
> Update Android SDK 5.1.5

- CHANGELOG.md
- android/build.gradle
- ios/unico_check.podspec
- pubspec.yaml
Release version 4.1.0
Update iOS to 2.4.0
Update Android to 5.2.0
> Release 4.1.0

- CHANGELOG.md
- android/build.gradle
- ios/unico_check.podspec
- pubspec.yaml
> 
- update iOS to `2.8.0`
- update Android to `5.9.0`
> feat: update native modules

- CHANGELOG.md
- ios/unico_check.podspec
- pubspec.yaml
> Rollback iOS version to `2.9.0`
> chore: update ios native version

- CHANGELOG.md
- pubspec.yaml
* Adjust changeling
* Adjust pubspec version to `2.5.2`
> feat: release 4.5.2

- CHANGELOG.md
- ios/unico_check.podspec
- pubspec.yaml
> new version 4.8.0
> update iOS native version to '2.12.1';
> update android native version to '5.13.0'
> feature: release 4.8.0

- ios/unico_check.podspec
> Update iOS to latest version
> update iOS podspec dependency
> feat: update iOS to 2.14.0

- android/build.gradle
> Update Android to latest version
> update gradle dependency
> feat: update android 5.14.1

- CHANGELOG.md
- pubspec.yaml
> feat: Bump Version 4.8.1

- CHANGELOG.md
- android/build.gradle
- android/src/main/AndroidManifest.xml
- ios/unico_check.podspec
- pubspec.yaml
> Describe what motivates you to submit this change
> List all changes made
> Describe how to test this change (optional)
> feat: Bump Version 4.8.2

- CHANGELOG.md
- android/build.gradle
- pubspec.yaml
> feat: Bump Version 4.8.3 hotfix android 5.15.0

- CHANGELOG.md
- android/build.gradle
- ios/Classes/AcessoBioCamera.swift
- ios/unico_check.podspec
- pubspec.yaml
> Update native dependencies.
> Update Android SDK to 5.16.0;
> Update iOS SDK to 2.15.1;
> Feature: release 4.9.0

- CHANGELOG.md
- android/build.gradle
- pubspec.yaml
> feat: Bump Version 5.16.0-beta Android

- CHANGELOG.md
- android/build.gradle
- ios/unico_check.podspec
- pubspec.yaml
> update native versions
> update android version to `5.17.0`;
> update iOS version to `2.15.2`
> Feat: release 4.10.0

- CHANGELOG.md
- android/build.gradle
- ios/unico_check.podspec
- pubspec.yaml
> Update android beta `5.18.0-beta` and iOS `2.15.5`
> feat: update beta test android

- CHANGELOG.md
- ios/unico_check.podspec
- lib/src/unico/domain/entities/unico.environment.dart
- lib/src/unico/domain/entities/unico.locale.types.dart
- pubspec.yaml
- test/src/unico/adapter/api/unico.check.camera.opener.default_test.dart
- test/src/unico/domain/mapper/open.camera.request.mapper_test.dart
> Update iOS native version
> iOS verstion to `2.16.1`
> feat: update ios native version to 2.16.1

- CHANGELOG.md
- android/build.gradle
- pubspec.yaml
> Update android native 5.25.0
> feat: update android native 5.25.0

- lib/unico_check.dart
> feat: export environment

- android/src/main/kotlin/com/unico_check/config/UnicoTheme.kt
- example/ios/Podfile
- example/lib/main.dart
- ios/Classes/config/UnicoTheme.swift
- lib/src/unico/adapter/repository/mappers/unico.theme.mapper.dart
- lib/src/unico/domain/entities/unico.theme.dart
This pull request includes several changes to the `UnicoTheme` class and related files to support new theme properties. The changes add support for `colorProgressBar` and `colorCancelButtonIcon` across different platforms and configurations.
* [`android/src/main/kotlin/com/unico_check/config/UnicoTheme.kt`](diffhunk://#diff-bc43663858885e0f065ef978aa450dc988eca4098e6efabf58818839d2459f1dR64-R67): Added `getColorProgressBar` method to return the color of the progress bar from the theme map.
* [`example/lib/main.dart`](diffhunk://#diff-72fd825ad17ce7800a2078e06f0dff1e12836ee59760465e78d9a5d222cebd15L39-R41): Updated `_MyHomePageState` to include `colorProgressBar` and `colorCancelButtonIcon` in the theme configuration.
* [`ios/Classes/config/UnicoTheme.swift`](diffhunk://#diff-d2b79b1e9a11cb …
> Feat: adjust customization

- CHANGELOG.md
- android/build.gradle
- ios/unico_check.podspec
- pubspec.yaml
> Update android and iOS native versions.
This pull request includes updates to both the Android and iOS SDKs, as well as version updates across various configuration files. The most important changes are listed below:
* Updated the Android SDK to version `5.29.0` in `android/build.gradle`.
* Updated the iOS SDK to version `2.16.8` in `ios/unico_check.podspec`.
* Updated the package version to `4.23.0` in `pubspec.yaml`.
* Added release notes for version `4.23.0` in `CHANGELOG.md`.
> feat: release 4.23.0

- .github/workflows/publish.yml
> Describe what motivates you to submit this change
> List all changes made
> Describe how to test this change (optional)
> infra: force use main branch when checkout

- example/android/app/build.gradle
- example/android/build.gradle
- example/android/settings.gradle
https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply
> Deprecated imperative apply of Flutter's Gradle plugins
